export const MOBILE_BREAKPOINT_PX = 1024;
export const MOBILE_LABEL_BREAKPOINT_PX = 350;
export const HIDE_LOGOUT_TEXT_BREAKPOINT_PX = 420;

export default {
  MOBILE_BREAKPOINT_PX,
  MOBILE_LABEL_BREAKPOINT_PX,
  HIDE_LOGOUT_TEXT_BREAKPOINT_PX,
};
